#!/bin/sh 

dir=/home/jplank/cs360/labs/Lab-4-Fakemake
ge="$dir/Gradescript-Examples"

if [ $# -ne 0 ]; then
  echo 'usage: gradeall' >&2
  exit 1
fi

enum=1
n=0
while [ $enum -le 100 ]; do
  out=`$dir/gradescript $enum  | head -n 1`
  echo $out
  n=`echo $n $out | awk '{ print $1 + ($NF == "correct.") }'`

  chmod 0700 test-dir your-dir 2>/dev/null
  chmod -R 0700 test-dir your-dir 2>/dev/null
  rm -rf test-dir your-dir  tarfile
  rm -f tmp-???-test-stdout.txt tmp-???-test-stderr.txt

  enum=`echo $enum | awk '{ print $1+1 }'`
done

echo ""

echo "$n Correct out of 100"
