#!/bin/sh 

dir=/home/jplank/cs360/labs/Lab-5-Tarc
ge="$dir/Gradescript-Examples"

if [ $# -ne 0 ]; then
  echo 'usage: gradeall' >&2
  exit 1
fi

enum=1
n=0
while [ $enum -le 100 ]; do
  out=`$dir/gradescript $enum  | head -n 1`
  echo $out
  n=`echo $n $out | awk '{ print $1 + ($NF == "correct.") }'`

  rm -f tmp-???-correct-stderr.txt tmp-???-correct-stdout.txt tmp-???-correct-tarfile.txt \
  rm -f tmp-???-your-stderr.txt tmp-???-your-stdout.txt tmp-???-your-tarfile.txt \

  enum=`echo $enum | awk '{ print $1+1 }'`
done

echo ""

echo "$n Correct out of 100"
