#!/bin/sh 

dir=/home/jplank/cs360/labs/Lab-9-Chat

if [ $# -ne 3 ]; then
  echo 'usage: gradescript problem_number (1-100) host port' >&2
  exit 1
fi

if [ "$1" -gt 0 -a "$1" -le 100 ]; then
  enum=`echo $1 | awk '{ printf "%03d\n", $1 }'`
else
  echo 'usage: gradescript problem_number (1-100)' >&2
  exit 1
fi
  
grader=$dir/laba-tester
  
call="sh -c '$grader $enum $2 $3 > tmp-grader-stdout.txt 2>tmp-grader-stderr.txt'"
$grader $enum $2 $3 > tmp-grader-stdout.txt 2>tmp-grader-stderr.txt

if [ `tail -n 1 tmp-grader-stdout.txt | grep 'Events correctly processed' | wc | awk '{ print $1 }'` -ne 1 ]; then
  echo "Problem $enum is incorrect."
  echo ""
  echo "Check tmp-grader-stdout.txt, tmp-grader-stderr.txt, tmp-inputfile.txt and output-*.txt"
  echo ""
  echo "TEST:"
  echo ""
  echo "$call"
  echo ""
else 
  echo "Problem $enum is correct."
  echo ""
  echo "Test: $call" 
  rm -f tmp-* 2>/dev/null
fi
