#!/bin/sh 

dir=/home/jplank/cs360/labs/Lab-9-Chat
ge="$dir/Gradescript-Examples"

if [ $# -ne 2 ]; then
  echo 'usage: gradeall host port' >&2
  exit 1
fi

enum=1
n=0
while [ $enum -le 100 ]; do
  out=`$dir/gradescript $enum $1 $2 | head -n 1`
  echo $out
  n=`echo $n $out | awk '{ print $1 + ($NF == "correct.") }'`

  hn=`/bin/hostname`
  rm -f tmp-*-$hn-* 2>/dev/null

  enum=`echo $enum | awk '{ print $1+1 }'`
done

echo ""

echo "$n Correct out of 100"
