#!/bin/sh 

dir=/home/jplank/cs360/labs/Lab-1-Chain-Heal
ge="$dir/Gradescript-Examples"

if [ $# -ne 1 ]; then
  echo 'usage: gradescript problem_number (1-100)' >&2
  exit 1
fi

if [ "$1" -gt 0 -a "$1" -le 100 ]; then
  enum=`echo $1 | awk '{ printf "%03d\n", $1 }'`
else
  echo 'usage: gradescript problem_number (1-100)' >&2
  exit 1
fi
  
program=chain_heal
  
if [ ! -f $program ]; then
  echo "Problem $enum is incorrect."
  echo ""
  echo "Your program $program does not exist."
  exit 0
fi

rm -f tmp-$enum-test-stdout.txt tmp-$enum-test-stderr.txt tmp-$enum-correct-stdout.txt tmp-$enum-correct-stderr.txt tmp-$enum-check.txt

$dir/$program < $ge/$enum.txt `cat $ge/$enum.cl` > tmp-$enum-correct-stdout.txt 2> tmp-$enum-correct-stderr.txt
./$program < $ge/$enum.txt `cat $ge/$enum.cl` > tmp-$enum-test-stdout.txt 2> tmp-$enum-test-stderr.txt
call="./$program < $ge/$enum.txt "`cat $ge/$enum.cl`

err=`diff tmp-$enum-correct-stderr.txt tmp-$enum-test-stderr.txt | wc | awk '{ print $1 }'`
out=0
cval=0
yval=0

if [ $err = 0 ]; then
  $dir/chain_heal_check `cat $ge/$enum.cl` $ge/$enum.txt < tmp-$enum-test-stdout.txt > tmp-$enum-check.txt 2>&1
  out=`cat tmp-$enum-check.txt | wc | awk '{ print $1 }'`
  if [ $out = 0 ]; then
    cval=`tail -n 1 tmp-$enum-correct-stdout.txt | awk '{ print $2 }'`
    yval=`tail -n 1 tmp-$enum-test-stdout.txt | awk '{ print $2 }'`
  fi
fi

if [ $out != 0 -o $err != 0 -o $cval != $yval ]; then
  echo "Problem $enum is incorrect."
  echo ""
  if [ $out != 0 ]; then
    echo "Your standard output is not a correct path."
    echo "The output of chain_heal_check is in the file tmp-$enum-check.txt."
  fi
  if [ $err != 0 ]; then
    echo "Your standard error does not match the correct one."
  fi
  if [ $yval != $cval ]; then
    echo "Your total healing ($yval) does not match the correct healing ($cval)."
  fi
  echo ""
  echo "TEST:"
  echo ""
  echo "$call"
  echo ""
  echo "FILES:"
  echo ""
  echo "Your standard output is in tmp-$enum-test-stdout.txt."
  echo "Your standard error  is in tmp-$enum-test-stderr.txt."
  if [ -f tmp-$enum-check.txt ]; then
    echo "The output of chain_heal_check is in the file tmp-$enum-check.txt."
  fi
  echo ""
  echo "The correct standard output is in tmp-$enum-correct-stdout.txt."
  echo "The correct standard error  is in tmp-$enum-correct-stderr.txt."
  echo ""
  echo "Look at correct files and your files, and figure out your mistake."
  echo "Please remember to delete these files when you are finished."
else 
  echo "Problem $enum is correct."
  echo ""
  echo "Test:" 
  echo "$call" 
  rm -f tmp-$enum-test-stdout.txt tmp-$enum-test-stderr.txt tmp-$enum-correct-stdout.txt \
        tmp-$enum-correct-stderr.txt tmp-$enum-check.txt
fi
